### ISSUE TITLE
Behat support for SSL.

### ISSUE THREAD

**Issue by damontgomery** [palantirnet/drupal-skeleton#88]
I ended up having to set the base url to `http` instead of `https` to get Circle CI to pass.

I tried the HTTPS and I was getting errors because my local cert is not valid.

I made this change to get it to work locally, but still get an error on Circle CI:
```
default:
  extensions:
    Behat\MinkExtension:
      sessions:
        my_session:
          goutte:
            guzzle_parameters:
              verify: false
        my_javascript_session:
          selenium2:
            wd_host: "http://127.0.0.1:8643/wd/hub"
      default_session: my_session
      javascript_session: my_javascript_session
      base_url: https://[MY SITE].local
```

error:
```
Given I am not logged in: cURL error 35: Unknown SSL protocol error in connection to [REDACTED].local:8000  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\ConnectException)
```

See https://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html

```
guzzle_parameters:
  curl.options:
    CURLOPT_SSLVERSION: CURL_SSLVERSION_TLSv1_3
```
